version: '3'
services:
  nginx:
    image: nginx:1.13
    ports:
      - "8000:80"
    volumes:
      - ./src:/src
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:7.1-fpm
    volumes:
      - ./src:/src